In [1]:
import os
import yaml
import pytz
import requests
import numpy as np
import pandas as pd
from datetime import datetime
from dotenv import load_dotenv

# import functions from bookie_grabber
from bookie_grabber import *

# import betfair_api funcs
from betfair_api import *

load_dotenv()

True

In [ ]:
# ┌─────────────────────────────────────────────────────────┐
# │  1. SPORTS                                              │
# │  What sports are available?                             │
# │  GET /v3/sports                                         │
# │  Returns: Football, Basketball, Tennis, etc.            │
# └──────────────────┬──────────────────────────────────────┘
#                    │
#                    ↓
# ┌─────────────────────────────────────────────────────────┐
# │  2. LEAGUES                                             │
# │  What leagues exist in a sport?                         │
# │  GET /v3/leagues?sport=football                         │
# │  Returns: Premier League, La Liga, Bundesliga, etc.     │
# └──────────────────┬──────────────────────────────────────┘
#                    │
#                    ↓
# ┌─────────────────────────────────────────────────────────┐
# │  3. EVENTS                                              │
# │  What matches are coming up?                            │
# │  GET /v3/events?sport=football&league=premier-league    │
# │  Returns: Man Utd vs Liverpool, Chelsea vs Arsenal, etc.│
# └──────────────────┬──────────────────────────────────────┘
#                    │
#                    ↓
# ┌─────────────────────────────────────────────────────────┐
# │  4. ODDS                                                │
# │  What are the betting odds?                             │
# │  GET /v3/odds?eventId=123456&bookmakers=Bet365,Unibet   │
# │  Returns: Odds from multiple bookmakers                 │
# └─────────────────────────────────────────────────────────┘

In [ ]:
# "status": "pending" for events
# Example usage
df_totals, df_btts = main()

In [ ]:
# Hey mate, the volume is already available, listed under “depth” in the markets array.

In [ ]:
api_key = load_env()
odds = get_event_odds(api_key, 61300797)

In [ ]:
for bookmaker, markets in odds.get("bookmakers", {}).items():
    for m in markets:
        print(f"{bookmaker} - {m.get('name')}" )

In [ ]:
btts = []
for bookmaker, markets in odds.get("bookmakers", {}).items():
    for market in markets:
        if market.get("name") == "Both Teams to Score" or market.get("name") == "Both Teams To Score":
            for o in market.get("odds", []):
                    btts.append({
                        "bookmaker": bookmaker,
                        "market": market.get("name"),
                        "yes": o.get("yes"),
                        "no": o.get("no"),
                    })
btts

In [18]:
# confirm that 
dft = pd.read_csv(r"data/exports/english_premier_league/totals/totals_hdp_1.5_20251206.csv")
dfb= pd.read_csv(r"data/exports/english_premier_league/btts/btts_20251206.csv")

In [14]:
session_token = get_session_token()
print("SESSION TOKEN:", session_token)
# Pick a league from config (for example, first league)
league_name = LEAGUES[0]["name"]
df = get_ou_volume(session_token, league_name)

SESSION TOKEN: do+rEvNgcWaQqORDDrziO8IHzNAhl3SlGlYeaaD7f2o=

In [12]:
TEAM_MAP = load_team_map()
df = df[['event', 'line', 'total_volume']]
dfb['bf_team_name_home'] = dfb['home_team'].map(TEAM_MAP)
dfb['bf_team_name_away'] = dfb['away_team'].map(TEAM_MAP)
dfb['bf_merge_key'] = dfb['bf_team_name_home'] + " v " + dfb['bf_team_name_away']
dfbtv = dfb.merge(df[df.line == 'Both teams to Score?'], how='left', left_on='bf_merge_key', right_on='event')
dfbtv[dfb.columns]

,event_id,home_team,away_team,competition,match_time,odds_time,Bet365_no_odds,Bet365_yes_odds,Betfair_Exchange_no_odds,Betfair_Exchange_yes_odds,Yes RPD,No RPD,hours_until_KO,bf_team_name_home,bf_team_name_away,bf_merge_key
0,61300795,AFC Bournemouth,Chelsea FC,England - Premier League,2025-12-06 23:00:00+08:00,2025-12-06 19:54:18.080414+08:00,2.375,1.533,2.60,1.61,4.900,9.045,3.094978,Bournemouth,Chelsea,Bournemouth v Chelsea
1,61300797,Aston Villa,Arsenal FC,England - Premier League,2025-12-06 20:30:00+08:00,2025-12-06 19:54:18.080414+08:00,1.909,1.909,2.04,1.93,1.094,6.635,0.594978,Aston Villa,Arsenal,Aston Villa v Arsenal
2,61300799,Brighton & Hove Albion,West Ham United,England - Premier League,2025-12-07 22:00:00+08:00,2025-12-06 19:54:18.080414+08:00,2.050,1.700,2.26,1.76,3.468,9.745,26.094978,Brighton,West Ham,Brighton v West Ham
3,61300801,Everton FC,Nottingham Forest,England - Premier League,2025-12-06 23:00:00+08:00,2025-12-06 19:54:18.080414+08:00,1.950,1.800,1.99,1.97,9.019,2.030,3.094978,Everton,Nottm Forest,Everton v Nottm Forest
4,61300803,Fulham FC,Crystal Palace,England - Premier League,2025-12-08 00:30:00+08:00,2025-12-06 19:54:18.080414+08:00,1.950,1.800,2.10,1.87,3.815,7.407,28.594978,Fulham,Crystal Palace,Fulham v Crystal Palace
5,61300805,Leeds United,Liverpool FC,England - Premier League,2025-12-07 01:30:00+08:00,2025-12-06 19:54:18.080414+08:00,2.000,1.750,2.20,1.79,2.260,9.524,5.594978,Leeds,Liverpool,Leeds v Liverpool
6,61300807,Manchester City,Sunderland AFC,England - Premier League,2025-12-06 23:00:00+08:00,2025-12-06 19:54:18.080414+08:00,1.909,1.909,1.95,2.00,4.656,2.125,3.094978,Man City,Sunderland,Man City v Sunderland
7,61300809,Newcastle United,Burnley FC,England - Premier League,2025-12-06 23:00:00+08:00,2025-12-06 19:54:18.080414+08:00,1.800,1.950,1.87,2.10,7.407,3.815,3.094978,Newcastle,Burnley,Newcastle v Burnley
8,61300811,Tottenham Hotspur,Brentford FC,England - Premier League,2025-12-06 23:00:00+08:00,2025-12-06 19:54:18.080414+08:00,2.000,1.750,2.20,1.80,2.817,9.524,3.094978,Tottenham,Brentford,Tottenham v Brentford
9,61300815,Arsenal FC,Wolverhampton Wanderers,England - Premier League,2025-12-14 04:00:00+08:00,2025-12-06 19:54:18.080414+08:00,1.571,2.250,1.64,2.24,1.000,4.298,176.094978,Arsenal,Wolves,Arsenal v Wolves
10,61300817,Brentford FC,Leeds United,England - Premier League,2025-12-15 00:30:00+08:00,2025-12-06 19:54:18.080414+08:00,2.000,1.750,2.04,1.77,1.136,1.980,196.594978,Brentford,Leeds,Brentford v Leeds
11,61300819,Burnley FC,Fulham FC,England - Premier League,2025-12-14 01:30:00+08:00,2025-12-06 19:54:18.080414+08:00,1.909,1.909,1.96,1.84,1.000,2.636,173.594978,Burnley,Fulham,Burnley v Fulham
12,61300821,Chelsea FC,Everton FC,England - Premier League,2025-12-13 23:00:00+08:00,2025-12-06 19:54:18.080414+08:00,1.909,1.909,1.01,1.01,1.000,1.000,171.094978,Chelsea,Everton,Chelsea v Everton
13,61300823,Crystal Palace,Manchester City,England - Premier League,2025-12-14 22:00:00+08:00,2025-12-06 19:54:18.080414+08:00,2.200,1.615,1.01,1.01,1.000,1.000,194.094978,Crystal Palace,Man City,Crystal Palace v Man City
14,61300825,Liverpool FC,Brighton & Hove Albion,England - Premier League,2025-12-13 23:00:00+08:00,2025-12-06 19:54:18.080414+08:00,2.250,1.571,2.38,1.60,1.829,5.616,171.094978,Liverpool,Brighton,Liverpool v Brighton
15,61300829,Nottingham Forest,Tottenham Hotspur,England - Premier League,2025-12-14 22:00:00+08:00,2025-12-06 19:54:18.080414+08:00,2.050,1.700,2.20,1.71,1.000,7.059,194.094978,Nottm Forest,Tottenham,Nottm Forest v Tottenham
16,61300831,Sunderland AFC,Newcastle United,England - Premier League,2025-12-14 22:00:00+08:00,2025-12-06 19:54:18.080414+08:00,2.000,1.750,2.04,1.77,1.136,1.980,194.094978,Sunderland,Newcastle,Sunderland v Newcastle
17,61300833,West Ham United,Aston Villa,England - Premier League,2025-12-14 22:00:00+08:00,2025-12-06 19:54:18.080414+08:00,2.100,1.666,2.20,1.70,2.020,4.651,194.094978,West Ham,Aston Villa,West Ham v Aston Villa
18,64618978,Wolverhampton Wanderers,Manchester United,England - Premier League,2025-12-09 04:00:00+08:00,2025-12-06 19:54:18.080414+08:00,2.100,1.666,2.26,1.74,4.345,7.339,56.094978,Wolves,Man Utd,Wolves v Man Utd
19,65586346,Manchester United,AFC Bournemouth,England - Premier League,2025-12-16 04:00:00+08:00,2025-12-06 19:54:18.080414+08:00,2.375,1.533,2.20,1.59,3.650,1.000,224.094978,Man Utd,Bournemouth,Man Utd v Bournemouth

In [ ]:
df[df.line == 'Both teams to Score?'].shape

In [15]:
df.line.unique()

array(['Over/Under 2.5 Goals', 'Both teams to Score?',
       'Over/Under 3.5 Goals', 'Over/Under 1.5 Goals'], dtype=object)

In [19]:
TEAM_MAP = load_team_map()
df = df[['event', 'line', 'total_volume']]
dft['bf_team_name_home'] = dft['home_team'].map(TEAM_MAP)
dft['bf_team_name_away'] = dft['away_team'].map(TEAM_MAP)
dft['bf_merge_key'] = dft['bf_team_name_home'] + " v " + dft['bf_team_name_away']
dfbtv = dft.merge(df[df.line == 'Over/Under 1.5 Goals'], how='left', left_on='bf_merge_key', right_on='event')

In [21]:
df[df.line == 'Over/Under 1.5 Goals'].event.unique()

array(['Aston Villa v Arsenal', 'Tottenham v Brentford',
       'Man City v Sunderland', 'Everton v Nottm Forest',
       'Newcastle v Burnley', 'Bournemouth v Chelsea',
       'Leeds v Liverpool', 'Brighton v West Ham',
       'Fulham v Crystal Palace', 'Wolves v Man Utd'], dtype=object)

In [22]:
dft.bf_merge_key.unique()

array(['Bournemouth v Chelsea', 'Aston Villa v Arsenal',
       'Brighton v West Ham', 'Everton v Nottm Forest',
       'Fulham v Crystal Palace', 'Leeds v Liverpool',
       'Man City v Sunderland', 'Newcastle v Burnley',
       'Tottenham v Brentford', 'Arsenal v Wolves', 'Brentford v Leeds',
       'Burnley v Fulham', 'Chelsea v Everton',
       'Crystal Palace v Man City', 'Liverpool v Brighton',
       'Nottm Forest v Tottenham', 'Sunderland v Newcastle',
       'West Ham v Aston Villa', 'Wolves v Man Utd',
       'Man Utd v Bournemouth'], dtype=object)

In [23]:
dfbtv

,event_id,home_team,away_team,competition,match_time,odds_time,Bet365_over_odds,Bet365_under_odds,Betfair_Exchange_over_odds,Betfair_Exchange_under_odds,...,bf_merge_key,marketId,line_x,total_volume_x,event_x,kickoff,hours_until_KO,event_y,line_y,total_volume_y
0,61300795,AFC Bournemouth,Chelsea FC,England - Premier League,2025-12-06 23:00:00+08:00,2025-12-06 21:31:36.992163+08:00,1.200,4.500,1.21,5.40,...,Bournemouth v Chelsea,1.251156,Over/Under 1.5 Goals,3393.342624,Bournemouth v Chelsea,2025-12-06T15:00:00.000Z,1.473058,Bournemouth v Chelsea,Over/Under 1.5 Goals,3047.307137
1,61300797,Aston Villa,Arsenal FC,England - Premier League,2025-12-06 20:30:00+08:00,2025-12-06 21:31:36.992163+08:00,NaN,NaN,1.26,4.81,...,Aston Villa v Arsenal,1.251156,Over/Under 1.5 Goals,354877.646100,Aston Villa v Arsenal,2025-12-06T12:30:00.000Z,-1.026942,Aston Villa v Arsenal,Over/Under 1.5 Goals,66881.566481
2,61300799,Brighton & Hove Albion,West Ham United,England - Premier League,2025-12-07 22:00:00+08:00,2025-12-06 21:31:36.992163+08:00,1.200,4.500,1.22,5.20,...,Brighton v West Ham,1.251156,Over/Under 1.5 Goals,58.667916,Brighton v West Ham,2025-12-07T14:00:00.000Z,24.473058,Brighton v West Ham,Over/Under 1.5 Goals,58.664994
3,61300801,Everton FC,Nottingham Forest,England - Premier League,2025-12-06 23:00:00+08:00,2025-12-06 21:31:36.992163+08:00,1.363,3.200,1.41,3.30,...,Everton v Nottm Forest,1.251157,Over/Under 1.5 Goals,3129.256690,Everton v Nottm Forest,2025-12-06T15:00:00.000Z,1.473058,Everton v Nottm Forest,Over/Under 1.5 Goals,3116.171247
4,61300803,Fulham FC,Crystal Palace,England - Premier League,2025-12-08 00:30:00+08:00,2025-12-06 21:31:36.992163+08:00,1.333,3.400,1.38,3.50,...,Fulham v Crystal Palace,1.251156,Over/Under 1.5 Goals,58.908852,Fulham v Crystal Palace,2025-12-07T16:30:00.000Z,26.973058,Fulham v Crystal Palace,Over/Under 1.5 Goals,58.905918
5,61300805,Leeds United,Liverpool FC,England - Premier League,2025-12-07 01:30:00+08:00,2025-12-06 21:31:36.992163+08:00,1.250,4.000,1.28,4.33,...,Leeds v Liverpool,1.251157,Over/Under 1.5 Goals,5116.637364,Leeds v Liverpool,2025-12-06T17:30:00.000Z,3.973058,Leeds v Liverpool,Over/Under 1.5 Goals,4942.154320
6,61300807,Manchester City,Sunderland AFC,England - Premier League,2025-12-06 23:00:00+08:00,2025-12-06 21:31:36.992163+08:00,1.166,5.000,1.18,6.00,...,Man City v Sunderland,1.251156,Over/Under 1.5 Goals,13193.253800,Man City v Sunderland,2025-12-06T15:00:00.000Z,1.473058,Man City v Sunderland,Over/Under 1.5 Goals,10851.899578
7,61300809,Newcastle United,Burnley FC,England - Premier League,2025-12-06 23:00:00+08:00,2025-12-06 21:31:36.992163+08:00,1.200,4.500,1.24,5.00,...,Newcastle v Burnley,1.251156,Over/Under 1.5 Goals,3645.964020,Newcastle v Burnley,2025-12-06T15:00:00.000Z,1.473058,Newcastle v Burnley,Over/Under 1.5 Goals,1786.531768
8,61300811,Tottenham Hotspur,Brentford FC,England - Premier League,2025-12-06 23:00:00+08:00,2025-12-06 21:31:36.992163+08:00,1.285,3.750,1.33,3.90,...,Tottenham v Brentford,1.251157,Over/Under 1.5 Goals,6168.182458,Tottenham v Brentford,2025-12-06T15:00:00.000Z,1.473058,Tottenham v Brentford,Over/Under 1.5 Goals,5855.637743
9,61300815,Arsenal FC,Wolverhampton Wanderers,England - Premier League,2025-12-14 04:00:00+08:00,2025-12-06 21:31:36.992163+08:00,1.222,4.333,1.19,3.49,...,Arsenal v Wolves,NaN,NaN,NaN,NaN,NaN,174.473058,NaN,NaN,NaN
10,61300817,Brentford FC,Leeds United,England - Premier League,2025-12-15 00:30:00+08:00,2025-12-06 21:31:36.992163+08:00,1.285,3.750,1.26,2.66,...,Brentford v Leeds,NaN,NaN,NaN,NaN,NaN,194.973058,NaN,NaN,NaN
11,61300819,Burnley FC,Fulham FC,England - Premier League,2025-12-14 01:30:00+08:00,2025-12-06 21:31:36.992163+08:00,1.333,3.400,1.29,2.87,...,Burnley v Fulham,NaN,NaN,NaN,NaN,NaN,171.973058,NaN,NaN,NaN
12,61300821,Chelsea FC,Everton FC,England - Premier League,2025-12-13 23:00:00+08:00,2025-12-06 21:31:36.992163+08:00,1.285,3.750,1.24,3.01,...,Chelsea v Everton,NaN,NaN,NaN,NaN,NaN,169.473058,NaN,NaN,NaN
13,61300823,Crystal Palace,Manchester City,England - Premier League,2025-12-14 22:00:00+08:00,2025-12-06 21:31:36.992163+08:00,1.222,4.333,1.05,1.26,...,Crystal Palace v Man City,NaN,NaN,NaN,NaN,NaN,192.473058,NaN,NaN,NaN
14,61300825,Liverpool FC,Brighton & Hove Albion,England - Premier League,2025-12-13 23:00:00+08:00,2025-12-06 21:31:36.992163+08:00,1.166,5.000,1.16,3.49,...,Liverpool v Brighton,NaN,NaN,NaN,NaN,NaN,169.473058,NaN,NaN,NaN
15,61300829,Nottingham Forest,Tottenham Hotspur,England - Premier League,2025-12-14 22:00:00+08:00,2025-12-06 21:31:36.992163+08:00,1.285,3.750,1.25,2.76,...,Nottm Forest v Tottenham,NaN,NaN,NaN,NaN,NaN,192.473058,NaN,NaN,NaN
16,61300831,Sunderland AFC,Newcastle United,England - Premier League,2025-12-14 22:00:00+08:00,2025-12-06 21:31:36.992163+08:00,1.300,3.500,1.27,2.90,...,Sunderland v Newcastle,NaN,NaN,NaN,NaN,NaN,192.473058,NaN,NaN,NaN
17,61300833,West Ham United,Aston Villa,England - Premier League,2025-12-14 22:00:00+08:00,2025-12-06 21:31:36.992163+08:00,1.250,4.000,1.22,2.98,...,West Ham v Aston Villa,NaN,NaN,NaN,NaN,NaN,192.473058,NaN,NaN,NaN
18,64618978,Wolverhampton Wanderers,Manchester United,England - Premier League,2025-12-09 04:00:00+08:00,2025-12-06 21:31:36.992163+08:00,1.222,4.333,1.25,4.70,...,Wolves v Man Utd,1.251157,Over/Under 1.5 Goals,0.000000,Wolves v Man Utd,2025-12-08T20:00:00.000Z,54.473058,Wolves v Man Utd,Over/Under 1.5 Goals,0.000000
19,65586346,Manchester United,AFC Bournemouth,England - Premier League,2025-12-16 04:00:00+08:00,2025-12-06 21:31:36.992163+08:00,1.166,5.000,1.16,3.49,...,Man Utd v Bournemouth,NaN,NaN,NaN,NaN,NaN,222.473058,NaN,NaN,NaN